version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge