const categories = [
    { "name": "Animals" },
    { "name": "Nature" },
    { "name": "Technology" },
    { "name": "Architecture" },
    { "name": "Food & Drink" },
    { "name": "Fashion" },
    { "name": "Sports" },
    { "name": "Music" },
    { "name": "Business" },
    { "name": "Health & Fitness" },
    { "name": "Travel" },
    { "name": "Education" },
    { "name": "Art & Design" },
    { "name": "Science" },
    { "name": "Entertainment" },
    { "name": "History" },
    { "name": "Lifestyle" },
    { "name": "Gaming" },
    { "name": "Movies" },
    { "name": "Photography" },
    { "name": "Social Media" },
    { "name": "Real Estate" },
    { "name": "Automotive" },
    { "name": "Home & Garden" },
    { "name": "Pets" },
    { "name": "Crafts" },
    { "name": "Holidays" },
    { "name": "Beauty" },
    { "name": "Parenting" },
    { "name": "Books" },
    { "name": "Marketing" },
    { "name": "Wedding" },
    { "name": "Events" },
    { "name": "DIY" },
    { "name": "Camping" },
    { "name": "Cycling" },
    { "name": "Hiking & Trekking" },
    { "name": "Equestrian" },
    { "name": "Personal Finance" },
    { "name": "Mobile & App Development" },
    { "name": "Artificial Intelligence" },
    { "name": "Space" },
    { "name": "Physics" },
    { "name": "Chemistry" },
    { "name": "Biology" },
    { "name": "Geography" }
];

export default categories;