const tags = [
    { name: "Lion", category: "Animals" }, // Animals
    { name: "Elephant", category: "Animals" }, // Animals
    { name: "Tiger", category: "Animals" }, // Animals
    { name: "Zebra", category: "Animals" }, // Animals
    { name: "Giraffe", category: "Animals" }, // Animals
    { name: "Cat", category: "Animals" }, // Animals
    { name: "Dog", category: "Animals" }, // Animals
    { name: "Koala", category: "Animals" }, // Animals
    { name: "Panda", category: "Animals" }, // Animals
    { name: "Kangaroo", category: "Animals" }, // Animals
    { name: "Forest", category: "Nature" }, // 
    { name: "Mountain", category: "Nature" }, // Nature
    { name: "Ocean", category: "Nature" }, // Nature
    { name: "River", category: "Nature" }, // Nature
    { name: "Desert", category: "Nature" }, // Nature
    { name: "Sunset", category: "Nature" }, // Nature
    { name: "Wildlife", category: "Nature" }, // Nature
    { name: "Rainforest", category: "Nature" }, // Nature
    { name: "Glacier", category: "Nature" }, // Nature
    { name: "Snow", category: "Nature" }, // Nature
    { name: "AI", category: "Technology" }, // 
    { name: "Blockchain", category: "Technology" }, // Technology
    { name: "Machine Learning", category: "Technology" }, // Technology
    { name: "Cloud Computing", category: "Technology" }, // Technology
    { name: "IoT", category: "Technology" }, // Technology
    { name: "Big Data", category: "Technology" }, // Technology
    { name: "Smartphones", category: "Technology" }, // Technology
    { name: "AR/VR", category: "Technology" }, // Technology
    { name: "Quantum Computing", category: "Technology" }, // Technology
    { name: "5G", category: "Technology" }, // Technology
    { name: "Buildings", category: "Architecture" }, // 
    { name: "Skyscrapers", category: "Architecture" }, // Architecture
    { name: "Bridges", category: "Architecture" }, // Architecture
    { name: "Interior Design", category: "Architecture" }, // Architecture
    { name: "Urban Planning", category: "Architecture" }, // Architecture
    { name: "Modern", category: "Architecture" }, // Architecture
    { name: "Historical", category: "Architecture" }, // Architecture
    { name: "Construction", category: "Architecture" }, // Architecture
    { name: "Landmarks", category: "Architecture" }, // Architecture
    { name: "Green Buildings", category: "Architecture" }, // Architecture
    { name: "Pizza", category: "Food & Drink" }, // Food & Drink
    { name: "Pasta", category: "Food & Drink" }, // Food & Drink
    { name: "Burger", category: "Food & Drink" }, // Food & Drink
    { name: "Ice Cream", category: "Food & Drink" }, // Food & Drink
    { name: "Coffee", category: "Food & Drink" }, // Food & Drink
    { name: "Smoothie", category: "Food & Drink" }, // Food & Drink
    { name: "Salad", category: "Food & Drink" }, // Food & Drink
    { name: "Sushi", category: "Food & Drink" }, // Food & Drink
    { name: "Steak", category: "Food & Drink" }, // Food & Drink
    { name: "Tacos", category: "Food & Drink" }, // Food & Drink
    { name: "Jeans", category: "Fashion" }, // Fashion
    { name: "T-shirt", category: "Fashion" }, // Fashion
    { name: "Dress", category: "Fashion" }, // Fashion
    { name: "Shoes", category: "Fashion" }, // Fashion
    { name: "Jacket", category: "Fashion" }, // Fashion
    { name: "Hat", category: "Fashion" }, // Fashion
    { name: "Bags", category: "Fashion" }, // Fashion
    { name: "Sunglasses", category: "Fashion" }, // Fashion
    { name: "Scarf", category: "Fashion" }, // Fashion
    { name: "Watch", category: "Fashion" }, // Fashion
    { name: "Football", category: "Sports" }, // Sports
    { name: "Basketball", category: "Sports" }, // Sports
    { name: "Baseball", category: "Sports" }, // Sports
    { name: "Tennis", category: "Sports" }, // Sports
    { name: "Soccer", category: "Sports" }, // Sports
    { name: "Golf", category: "Sports" }, // Sports
    { name: "Running", category: "Sports" }, // Sports
    { name: "Cycling", category: "Sports" }, // Sports
    { name: "Boxing", category: "Sports" }, // Sports
    { name: "Rugby", category: "Sports" }, // Sports
    { name: "Rock", category: "Music" },
    { name: "Pop", category: "Music" },
    { name: "Jazz", category: "Music" },
    { name: "Classical", category: "Music" },
    { name: "Hip-Hop", category: "Music" },
    { name: "Reggae", category: "Music" },
    { name: "Blues", category: "Music" },
    { name: "Electronic", category: "Music" },
    { name: "Country", category: "Music" },
    { name: "Indie", category: "Music" },
    { name: "Entrepreneurship", category: "Business" },
    { name: "Marketing", category: "Business" },
    { name: "Finance", category: "Business" },
    { name: "Leadership", category: "Business" },
    { name: "Networking", category: "Business" },
    { name: "E-commerce", category: "Business" },
    { name: "Management", category: "Business" },
    { name: "Startups", category: "Business" },
    { name: "Sales", category: "Business" },
    { name: "Strategy", category: "Business" },
    { name: "Yoga", category: "Health & Fitness" },
    { name: "Nutrition", category: "Health & Fitness" },
    { name: "Weight Loss", category: "Health & Fitness" },
    { name: "Cardio", category: "Health & Fitness" },
    { name: "Strength Training", category: "Health & Fitness" },
    { name: "Mental Health", category: "Health & Fitness" },
    { name: "Mindfulness", category: "Health & Fitness" },
    { name: "Fitness Plans", category: "Health & Fitness" },
    { name: "Healthy Eating", category: "Health & Fitness" },
    { name: "Exercise", category: "Health & Fitness" },
    { name: "Adventure", category: "Travel" },
    { name: "Beach", category: "Travel" },
    { name: "Wanderlust", category: "Travel" },
    { name: "Road Trip", category: "Travel" },
    { name: "Luxury Travel", category: "Travel" },
    { name: "Backpacking", category: "Travel" },
    { name: "Family Vacation", category: "Travel" },
    { name: "Solo Travel", category: "Travel" },
    { name: "Travel Tips", category: "Travel" },
    { name: "Destinations", category: "Travel" },
    { name: "Online Courses", category: "Education" },
    { name: "Self-Learning", category: "Education" },
    { name: "Study Tips", category: "Education" },
    { name: "College", category: "Education" },
    { name: "Tutoring", category: "Education" },
    { name: "E-learning", category: "Education" },
    { name: "STEM", category: "Education" },
    { name: "Language Learning", category: "Education" },
    { name: "Student Life", category: "Education" },
    { name: "Scholarships", category: "Education" },
    { name: "Digital Art", category: "Art & Design" },
    { name: "Illustration", category: "Art & Design" },
    { name: "Graphic Design", category: "Art & Design" },
    { name: "Painting", category: "Art & Design" },
    { name: "Sculpture", category: "Art & Design" },
    { name: "Typography", category: "Art & Design" },
    { name: "Animation", category: "Art & Design" },
    { name: "Photography", category: "Art & Design" },
    { name: "3D Modeling", category: "Art & Design" },
    { name: "Fashion Design", category: "Art & Design" },
    { name: "Physics", category: "Science" },
    { name: "Biology", category: "Science" },
    { name: "Chemistry", category: "Science" },
    { name: "Astronomy", category: "Science" },
    { name: "Environmental Science", category: "Science" },
    { name: "Geology", category: "Science" },
    { name: "Genetics", category: "Science" },
    { name: "Neuroscience", category: "Science" },
    { name: "Ecology", category: "Science" },
    { name: "Mathematics", category: "Science" },
    { name: "Movies", category: "Entertainment" },
    { name: "TV Shows", category: "Entertainment" },
    { name: "Music", category: "Entertainment" },
    { name: "Celebrities", category: "Entertainment" },
    { name: "Comics", category: "Entertainment" },
    { name: "Theater", category: "Entertainment" },
    { name: "Concerts", category: "Entertainment" },
    { name: "Podcasts", category: "Entertainment" },
    { name: "Events", category: "Entertainment" },
    { name: "Streaming", category: "Entertainment" },
    { name: "Ancient History", category: "History" },
    { name: "World War I", category: "History" },
    { name: "World War II", category: "History" },
    { name: "Civilizations", category: "History" },
    { name: "Historical Events", category: "History" },
    { name: "History of Art", category: "History" },
    { name: "Medieval History", category: "History" },
    { name: "Renaissance", category: "History" },
    { name: "Archaeology", category: "History" },
    { name: "History of Science", category: "History" },
    { name: "Artificial Intelligence", category: "Technology" },
    { name: "Blockchain", category: "Technology" },
    { name: "Machine Learning", category: "Technology" },
    { name: "Cybersecurity", category: "Technology" },
    { name: "Software Development", category: "Technology" },
    { name: "Gadgets", category: "Technology" },
    { name: "Augmented Reality", category: "Technology" },
    { name: "Virtual Reality", category: "Technology" },
    { name: "Cloud Computing", category: "Technology" },
    { name: "Internet of Things", category: "Technology" },
    { name: "Minimalism", category: "Lifestyle" },
    { name: "Sustainable Living", category: "Lifestyle" },
    { name: "Home Decor", category: "Lifestyle" },
    { name: "Personal Development", category: "Lifestyle" },
    { name: "Health & Wellness", category: "Lifestyle" },
    { name: "Self-Care", category: "Lifestyle" },
    { name: "Travel", category: "Lifestyle" },
    { name: "Food", category: "Lifestyle" },
    { name: "Fitness", category: "Lifestyle" },
    { name: "Mindfulness", category: "Lifestyle" },
    { name: "PC Gaming", category: "Gaming" },
    { name: "Console Gaming", category: "Gaming" },
    { name: "Mobile Gaming", category: "Gaming" },
    { name: "Esports", category: "Gaming" },
    { name: "RPG", category: "Gaming" },
    { name: "FPS", category: "Gaming" },
    { name: "Strategy Games", category: "Gaming" },
    { name: "MMO", category: "Gaming" },
    { name: "Multiplayer", category: "Gaming" },
    { name: "Indie Games", category: "Gaming" },
    { name: "Action", category: "Movies" },
    { name: "Drama", category: "Movies" },
    { name: "Comedy", category: "Movies" },
    { name: "Horror", category: "Movies" },
    { name: "Romance", category: "Movies" },
    { name: "Documentary", category: "Movies" },
    { name: "Thriller", category: "Movies" },
    { name: "Sci-Fi", category: "Movies" },
    { name: "Fantasy", category: "Movies" },
    { name: "Animated", category: "Movies" },
    { name: "Portrait", category: "Photography" },
    { name: "Landscape", category: "Photography" },
    { name: "Wedding", category: "Photography" },
    { name: "Wildlife", category: "Photography" },
    { name: "Street", category: "Photography" },
    { name: "Travel", category: "Photography" },
    { name: "Fashion", category: "Photography" },
    { name: "Black and White", category: "Photography" },
    { name: "Product", category: "Photography" },
    { name: "Sports", category: "Photography" },
    { name: "Facebook", category: "Social Media" },
    { name: "Instagram", category: "Social Media" },
    { name: "Twitter", category: "Social Media" },
    { name: "TikTok", category: "Social Media" },
    { name: "LinkedIn", category: "Social Media" },
    { name: "YouTube", category: "Social Media" },
    { name: "Snapchat", category: "Social Media" },
    { name: "Pinterest", category: "Social Media" },
    { name: "WhatsApp", category: "Social Media" },
    { name: "Reddit", category: "Social Media" },
    { name: "Residential", category: "Real Estate" },
    { name: "Commercial", category: "Real Estate" },
    { name: "Renting", category: "Real Estate" },
    { name: "Buying", category: "Real Estate" },
    { name: "Selling", category: "Real Estate" },
    { name: "Investment Properties", category: "Real Estate" },
    { name: "Luxury Homes", category: "Real Estate" },
    { name: "Foreclosures", category: "Real Estate" },
    { name: "Property Management", category: "Real Estate" },
    { name: "Real Estate Agent", category: "Real Estate" },
    { name: "Cars", category: "Automotive" },
    { name: "Motorcycles", category: "Automotive" },
    { name: "Trucks", category: "Automotive" },
    { name: "Electric Vehicles", category: "Automotive" },
    { name: "Car Reviews", category: "Automotive" },
    { name: "Vehicle Maintenance", category: "Automotive" },
    { name: "Auto Parts", category: "Automotive" },
    { name: "Driving Tips", category: "Automotive" },
    { name: "Motor Shows", category: "Automotive" },
    { name: "Car Accessories", category: "Automotive" },
    { name: "Gardening", category: "Home & Garden" },
    { name: "Home Improvement", category: "Home & Garden" },
    { name: "Interior Design", category: "Home & Garden" },
    { name: "Furniture", category: "Home & Garden" },
    { name: "Landscaping", category: "Home & Garden" },
    { name: "DIY Projects", category: "Home & Garden" },
    { name: "Home Decor", category: "Home & Garden" },
    { name: "Patio", category: "Home & Garden" },
    { name: "Sustainable Living", category: "Home & Garden" },
    { name: "Appliances", category: "Home & Garden" },
    { name: "Dogs", category: "Pets" },
    { name: "Cats", category: "Pets" },
    { name: "Fish", category: "Pets" },
    { name: "Birds", category: "Pets" },
    { name: "Small Animals", category: "Pets" },
    { name: "Pet Care", category: "Pets" },
    { name: "Pet Training", category: "Pets" },
    { name: "Pet Products", category: "Pets" },
    { name: "Pet Health", category: "Pets" },
    { name: "Pet Grooming", category: "Pets" }, { name: "Knitting", category: "Crafts" },
    { name: "Crochet", category: "Crafts" },
    { name: "Scrapbooking", category: "Crafts" },
    { name: "DIY Projects", category: "Crafts" },
    { name: "Painting", category: "Crafts" },
    { name: "Woodworking", category: "Crafts" },
    { name: "Origami", category: "Crafts" },
    { name: "Sewing", category: "Crafts" },
    { name: "Pottery", category: "Crafts" },
    { name: "Upcycling", category: "Crafts" },

    { name: "Christmas", category: "Holidays" },
    { name: "New Year", category: "Holidays" },
    { name: "Halloween", category: "Holidays" },
    { name: "Thanksgiving", category: "Holidays" },
    { name: "Easter", category: "Holidays" },
    { name: "Valentine's Day", category: "Holidays" },
    { name: "Fourth of July", category: "Holidays" },
    { name: "Labor Day", category: "Holidays" },
    { name: "Mother's Day", category: "Holidays" },
    { name: "Father's Day", category: "Holidays" },

    { name: "Makeup", category: "Beauty" },
    { name: "Skincare", category: "Beauty" },
    { name: "Haircare", category: "Beauty" },
    { name: "Nail Art", category: "Beauty" },
    { name: "Beauty Tips", category: "Beauty" },
    { name: "Cosmetics", category: "Beauty" },
    { name: "Anti-aging", category: "Beauty" },
    { name: "Beauty Tools", category: "Beauty" },
    { name: "Fragrances", category: "Beauty" },
    { name: "Beauty Tutorials", category: "Beauty" },

    { name: "Pregnancy", category: "Parenting" },
    { name: "Newborn Care", category: "Parenting" },
    { name: "Parenting Tips", category: "Parenting" },
    { name: "Toddler Activities", category: "Parenting" },
    { name: "Child Development", category: "Parenting" },
    { name: "Parenting Advice", category: "Parenting" },
    { name: "Raising Teens", category: "Parenting" },
    { name: "Discipline", category: "Parenting" },
    { name: "Family Time", category: "Parenting" },
    { name: "Kids Education", category: "Parenting" },

    { name: "Book Reviews", category: "Books" },
    { name: "Fiction", category: "Books" },
    { name: "Non-Fiction", category: "Books" },
    { name: "Self-Help", category: "Books" },
    { name: "Biographies", category: "Books" },
    { name: "Children's Books", category: "Books" },
    { name: "Book Recommendations", category: "Books" },
    { name: "Literature", category: "Books" },
    { name: "Ebooks", category: "Books" },
    { name: "Poetry", category: "Books" },

    { name: "Email Marketing", category: "Marketing" },
    { name: "SEO", category: "Marketing" },
    { name: "Social Media Ads", category: "Marketing" },
    { name: "Content Marketing", category: "Marketing" },
    { name: "PPC", category: "Marketing" },
    { name: "Affiliate Marketing", category: "Marketing" },
    { name: "Marketing Strategy", category: "Marketing" },
    { name: "Branding", category: "Marketing" },
    { name: "Influencer Marketing", category: "Marketing" },
    { name: "Marketing Automation", category: "Marketing" },
    { name: "Bridal Gowns", category: "Wedding" },
    { name: "Wedding Planning", category: "Wedding" },
    { name: "Bridal Party", category: "Wedding" },
    { name: "Wedding Invitations", category: "Wedding" },
    { name: "Honeymoon", category: "Wedding" },
    { name: "Wedding Decor", category: "Wedding" },
    { name: "Wedding Photography", category: "Wedding" },
    { name: "Destination Weddings", category: "Wedding" },
    { name: "Wedding Venues", category: "Wedding" },
    { name: "Wedding Dress Styles", category: "Wedding" }, { name: "Corporate Events", category: "Events" },
    { name: "Weddings", category: "Events" },
    { name: "Conferences", category: "Events" },
    { name: "Concerts", category: "Events" },
    { name: "Parties", category: "Events" },
    { name: "Festivals", category: "Events" },
    { name: "Trade Shows", category: "Events" },
    { name: "Fundraisers", category: "Events" },
    { name: "Expos", category: "Events" },
    { name: "Networking Events", category: "Events" },
    { name: "Home Projects", category: "DIY" },
    { name: "Crafts", category: "DIY" },
    { name: "Furniture Restoration", category: "DIY" },
    { name: "Home Decor", category: "DIY" },
    { name: "Gardening", category: "DIY" },
    { name: "Woodworking", category: "DIY" },
    { name: "Upcycling", category: "DIY" },
    { name: "Renovations", category: "DIY" },
    { name: "Outdoor DIY", category: "DIY" },
    { name: "Wall Art", category: "DIY" },

    { name: "Campgrounds", category: "Camping" },
    { name: "Camping Gear", category: "Camping" },
    { name: "Tent Setup", category: "Camping" },
    { name: "Survival Skills", category: "Camping" },
    { name: "Outdoor Cooking", category: "Camping" },
    { name: "Hiking Trails", category: "Camping" },
    { name: "Family Camping", category: "Camping" },
    { name: "Camping Essentials", category: "Camping" },
    { name: "Campfire Recipes", category: "Camping" },
    { name: "Backpacking", category: "Camping" },

    { name: "Mountain Biking", category: "Cycling" },
    { name: "Road Cycling", category: "Cycling" },
    { name: "Cycling Gear", category: "Cycling" },
    { name: "Cycling Events", category: "Cycling" },
    { name: "Biking Trails", category: "Cycling" },
    { name: "Cycling Tips", category: "Cycling" },
    { name: "Cycling Safety", category: "Cycling" },
    { name: "Cycling Fitness", category: "Cycling" },
    { name: "Cycling Clubs", category: "Cycling" },
    { name: "Bike Repair", category: "Cycling" },

    { name: "Trail Hiking", category: "Hiking & Trekking" },
    { name: "Mountain Hiking", category: "Hiking & Trekking" },
    { name: "Hiking Gear", category: "Hiking & Trekking" },
    { name: "Day Hikes", category: "Hiking & Trekking" },
    { name: "Backpacking", category: "Hiking & Trekking" },
    { name: "Hiking Trails", category: "Hiking & Trekking" },
    { name: "Hiking Safety", category: "Hiking & Trekking" },
    { name: "Hiking Tips", category: "Hiking & Trekking" },
    { name: "National Parks", category: "Hiking & Trekking" },
    { name: "Long-Distance Hiking", category: "Hiking & Trekking" },

    { name: "Equestrian Sports", category: "Equestrian" },
    { name: "Horseback Riding", category: "Equestrian" },
    { name: "Equestrian Gear", category: "Equestrian" },
    { name: "Horse Care", category: "Equestrian" },
    { name: "Equestrian Events", category: "Equestrian" },
    { name: "Horse Training", category: "Equestrian" },
    { name: "Riding Lessons", category: "Equestrian" },
    { name: "Show Jumping", category: "Equestrian" },
    { name: "Dressage", category: "Equestrian" },
    { name: "Equestrian Apparel", category: "Equestrian" },

    { name: "Budgeting", category: "Personal Finance" },
    { name: "Investing", category: "Personal Finance" },
    { name: "Saving Money", category: "Personal Finance" },
    { name: "Debt Management", category: "Personal Finance" },
    { name: "Retirement Planning", category: "Personal Finance" },
    { name: "Credit Score", category: "Personal Finance" },
    { name: "Financial Planning", category: "Personal Finance" },
    { name: "Personal Loans", category: "Personal Finance" },
    { name: "Emergency Fund", category: "Personal Finance" },
    { name: "Financial Independence", category: "Personal Finance" }, { name: "Astronomy", category: "Space" },
    { name: "Planets", category: "Space" },
    { name: "Stars", category: "Space" },
    { name: "Space Exploration", category: "Space" },
    { name: "Black Holes", category: "Space" },
    { name: "Galaxies", category: "Space" },
    { name: "Space Missions", category: "Space" },
    { name: "Space Telescopes", category: "Space" },
    { name: "Astrophysics", category: "Space" },
    { name: "Rocket Science", category: "Space" },

    { name: "Quantum Mechanics", category: "Physics" },
    { name: "Relativity", category: "Physics" },
    { name: "Particle Physics", category: "Physics" },
    { name: "Thermodynamics", category: "Physics" },
    { name: "Electromagnetism", category: "Physics" },
    { name: "Astrophysics", category: "Physics" },
    { name: "Nuclear Physics", category: "Physics" },
    { name: "Mechanics", category: "Physics" },
    { name: "String Theory", category: "Physics" },
    { name: "Fluid Dynamics", category: "Physics" },

    { name: "Organic Chemistry", category: "Chemistry" },
    { name: "Inorganic Chemistry", category: "Chemistry" },
    { name: "Physical Chemistry", category: "Chemistry" },
    { name: "Analytical Chemistry", category: "Chemistry" },
    { name: "Biochemistry", category: "Chemistry" },
    { name: "Chemical Reactions", category: "Chemistry" },
    { name: "Molecular Biology", category: "Chemistry" },
    { name: "Periodic Table", category: "Chemistry" },
    { name: "Chemical Engineering", category: "Chemistry" },
    { name: "Green Chemistry", category: "Chemistry" },

    { name: "Genetics", category: "Biology" },
    { name: "Cell Biology", category: "Biology" },
    { name: "Evolution", category: "Biology" },
    { name: "Microbiology", category: "Biology" },
    { name: "Ecology", category: "Biology" },
    { name: "Zoology", category: "Biology" },
    { name: "Botany", category: "Biology" },
    { name: "Human Anatomy", category: "Biology" },
    { name: "Biotechnology", category: "Biology" },
    { name: "Marine Biology", category: "Biology" },

    { name: "Continents", category: "Geography" },
    { name: "Countries", category: "Geography" },
    { name: "Landforms", category: "Geography" },
    { name: "Climate Zones", category: "Geography" },
    { name: "Mountains", category: "Geography" },
    { name: "Rivers", category: "Geography" },
    { name: "Oceans", category: "Geography" },
    { name: "Population Distribution", category: "Geography" },
    { name: "Geopolitics", category: "Geography" },
    { name: "Maps", category: "Geography" },

    { name: "Android Development", category: "Mobile & App Development" },
    { name: "iOS Development", category: "Mobile & App Development" },
    { name: "Cross-Platform Apps", category: "Mobile & App Development" },
    { name: "App Design", category: "Mobile & App Development" },
    { name: "App Testing", category: "Mobile & App Development" },
    { name: "React Native", category: "Mobile & App Development" },
    { name: "Swift", category: "Mobile & App Development" },
    { name: "Flutter", category: "Mobile & App Development" },
    { name: "App Store Optimization", category: "Mobile & App Development" },
    { name: "Mobile Security", category: "Mobile & App Development" },

    { name: "Machine Learning", category: "Artificial Intelligence" },
    { name: "Neural Networks", category: "Artificial Intelligence" },
    { name: "Deep Learning", category: "Artificial Intelligence" },
    { name: "Natural Language Processing", category: "Artificial Intelligence" },
    { name: "Computer Vision", category: "Artificial Intelligence" },
    { name: "Reinforcement Learning", category: "Artificial Intelligence" },
    { name: "AI Ethics", category: "Artificial Intelligence" },
    { name: "AI Algorithms", category: "Artificial Intelligence" },
    { name: "Robotics", category: "Artificial Intelligence" },
    { name: "Chatbots", category: "Artificial Intelligence" }

];

export default tags;